Compression (DBTL-1)
UBC-iGEM/dna-software pull request #29
Opened 2024-07-11 06:13 UTC by seb-hyland

**This code is heavily WIP at the moment and is untested. Exec.rs likely contains bugs or problems.**

The goal of this branch is to create:

1. A function that can arbitrarily run binaries on Windows/Linux (the binary will be written into a variable at compile time, then ran as an anonymous file at runtime)
2. Create the DBTL-1 variant of the compression implementation.

2024-07-22 22:32 UTC, seb-hyland commented
Provides compression and decompression mechanisms for lz4 and ts_zip. Exec.rs has been removed.

Compression takes `inpath:PathBuf` as input and outputs `Result<PathBuf, io::Error>` where `PathBuf` references the output file.
Decompression takes `inpath:PathBuf` and `outpath:PathBuf` as input and outputs `Result<()>`.

2024-07-23 06:04 UTC, lhao03 requested changes

2024-07-23 06:04 UTC, lhao03 commented on src-tauri/src/compressor.rs
>  }
can you add a test with quickcheck, just to quickly verify the decompress and compress work? 

Example: https://github.com/UBC-iGEM/dna-software/blob/main/src-tauri/src/encoder.rs#L75-L93

2024-07-23 06:09 UTC, lhao03 requested changes

2024-07-23 06:09 UTC, lhao03 commented on src-tauri/src/compressor.rs
>  pub trait Compressor {
also can you edit main.rs to add the compression during encode_sequence? 

https://github.com/UBC-iGEM/dna-software/blob/151916379ad340278c7996866aa9d992d4827303/src-tauri/src/main.rs#L35-L47


it should follow the old deleted sequence.rs almost exactly

https://github.com/UBC-iGEM/dna-software/blob/2b88993ed61a17033ea4fb30c28932cfbc92ae6f/src-tauri/src/sequence.rs#L11-L21

2024-07-28 16:00 UTC, lhao03 requested changes

2024-07-28 16:00 UTC, lhao03 commented on src-tauri/src/main.rs
> +    let bits = BitVec::<_, Msb0>::from_slice(&bytes);
To test this, do the below
![image](https://github.com/user-attachments/assets/6f9bf237-7adb-4b40-b771-89d5039a292b)

2024-07-28 17:07 UTC, lhao03 requested changes

2024-07-28 17:07 UTC, lhao03 commented on src-tauri/src/compressor.rs
> +        let outpath = Path::new(out_dir).join(filename).with_extension("lz4");
The assumption that this directory exists causes an error to be thrown; additionally, there is no handling of the case where the directory does not exist; I pushed a way to fix this, but this assumption is made in several other places in the code; please fix them and add proper handling of the case when the directory doesn't exist (either make it through Rust, or prompt the user to make it themselves).

2024-08-01 20:11 UTC, seb-hyland commented
Hi Lucy, I pushed up a hefty merge with my changes, your changes, and changes in main. This should include:
1. Your changes to `compress_lz4` to ensure the directory exists
2. My updates to `compressor.rs` and the updated `encode_sequence` function with my changes
3. I have kept your `dbg!("here");` macros; do you wish to keep those for now?

Although I haven't gone over everything again since the merge (except for resolving conflicts), the project is compiling and tests are passing (including the quickcheck for (de)compression). Do you wish to make a test for `encode_sequence`? I'm not sure how we would do that save for a test similar to `chaosDNA` (no assertion, just use some test sentence and print the output to CLI).

2024-08-02 15:34 UTC, lhao03 commented
> Hi Lucy, I pushed up a hefty merge with my changes, your changes, and changes in main. This should include:
> 
> 1. Your changes to `compress_lz4` to ensure the directory exists
> 2. My updates to `compressor.rs` and the updated `encode_sequence` function with my changes
> 3. I have kept your `dbg!("here");` macros; do you wish to keep those for now?
> 
> Although I haven't gone over everything again since the merge (except for resolving conflicts), the project is compiling and tests are passing (including the quickcheck for (de)compression). Do you wish to make a test for `encode_sequence`? I'm not sure how we would do that save for a test similar to `chaosDNA` (no assertion, just use some test sentence and print the output to CLI).

Yeah we can have a test for encode_sequence using quickcheck, I can set that up (but yeah it would be a test sentence or str that we can check compress -> bit -> base -> bit -> decompress)

2024-08-02 15:46 UTC, lhao03 approved these changes
Thanks for working on this Sebastian!

2024-08-02 15:46 UTC, merged